In [95]:
import pandas as pd
import numpy as np
import datetime, warnings, scipy
import seaborn as sns
import matplotlib as mpl

In [69]:
df1 = pd.read_csv(filepath_or_buffer = '../data/2008.csv')

### CRSDepTime is Scheduled Departure Time

In [48]:
df1.loc[:, "CRSDepTime"]

0          1955
1           735
2           620
3           930
4          1755
5          1915
6          1830
7          1040
8           615
9          1620
10          700
11         1510
12         1430
13          715
14         1700
15         1020
16         1425
17          745
18         1255
19         1325
20          705
21         1625
22         1840
23         1030
24          800
25         1455
26         1255
27         1925
28          635
29          730
           ...
7009698    1635
7009699    1221
7009700    1845
7009701    1500
7009702    1522
7009703    1910
7009704    1445
7009705     830
7009706    1440
7009707    1755
7009708     710
7009709    1520
7009710    1220
7009711    1041
7009712     843
7009713     815
7009714     545
7009715     850
7009716     936
7009717     600
7009718     847
7009719     640
7009720     800
7009721     615
7009722     750
7009723     959
7009724     835
7009725     700
7009726    1240
7009727    1103
Name: CRSDepTime, Length: 7009728, dtype: int64

In [6]:
#Convert the HHMM format to HH:MM format
def format_hour(hm):
    if pd.isnull(hm):
        return np.nan
    else:
        if hm == 2400: hm = 0
        hm = "{0:04d}".format(int(hm))
        newHM = datetime.time(int(hm[0:2]), int(hm[2:4]))
        return newHM

In [70]:
df1['CRSDepTime_Formatted'] = df1['CRSDepTime'].apply(format_hour)

In [51]:
df1['CRSDepTime_Formatted']

0          19:55:00
1          07:35:00
2          06:20:00
3          09:30:00
4          17:55:00
5          19:15:00
6          18:30:00
7          10:40:00
8          06:15:00
9          16:20:00
10         07:00:00
11         15:10:00
12         14:30:00
13         07:15:00
14         17:00:00
15         10:20:00
16         14:25:00
17         07:45:00
18         12:55:00
19         13:25:00
20         07:05:00
21         16:25:00
22         18:40:00
23         10:30:00
24         08:00:00
25         14:55:00
26         12:55:00
27         19:25:00
28         06:35:00
29         07:30:00
             ...
7009698    16:35:00
7009699    12:21:00
7009700    18:45:00
7009701    15:00:00
7009702    15:22:00
7009703    19:10:00
7009704    14:45:00
7009705    08:30:00
7009706    14:40:00
7009707    17:55:00
7009708    07:10:00
7009709    15:20:00
7009710    12:20:00
7009711    10:41:00
7009712    08:43:00
7009713    08:15:00
7009714    05:45:00
7009715    08:50:00
7009716    09:36:00
7009717    06:00:00
7009718    08:47:00
7009719    06:40:00
7009720    08:00:00
7009721    06:15:00
7009722    07:50:00
7009723    09:59:00
7009724    08:35:00
7009725    07:00:00
7009726    12:40:00
7009727    11:03:00
Name: CRSDepTime_Formatted, Length: 7009728, dtype: object

### Apply the same format for Scheduled Arrival Time, Departure Time, Arrival Time

In [71]:
df1['CRSArrTime_Formatted'] = df1['CRSArrTime'].apply(format_hour)
df1['CRSArrTime_Formatted']

0          22:25:00
1          10:00:00
2          07:50:00
3          11:00:00
4          19:25:00
5          21:10:00
6          19:40:00
7          11:50:00
8          06:50:00
9          16:55:00
10         09:15:00
11         17:25:00
12         14:25:00
13         07:10:00
14         16:55:00
15         10:10:00
16         16:25:00
17         09:55:00
18         15:10:00
19         14:35:00
20         08:10:00
21         17:35:00
22         19:50:00
23         11:40:00
24         09:10:00
25         16:05:00
26         16:10:00
27         22:35:00
28         09:45:00
29         10:20:00
             ...
7009698    17:58:00
7009699    13:59:00
7009700    20:06:00
7009701    16:42:00
7009702    18:23:00
7009703    20:16:00
7009704    16:22:00
7009705    10:08:00
7009706    17:04:00
7009707    20:15:00
7009708    08:37:00
7009709    17:18:00
7009710    15:52:00
7009711    13:03:00
7009712    10:21:00
7009713    15:26:00
7009714    06:50:00
7009715    10:05:00
7009716    11:19:00
7009717    07:49:00
7009718    10:10:00
7009719    07:53:00
7009720    10:26:00
7009721    09:07:00
7009722    08:59:00
7009723    11:50:00
7009724    10:23:00
7009725    08:56:00
7009726    14:37:00
7009727    14:18:00
Name: CRSArrTime_Formatted, Length: 7009728, dtype: object

### DepTime and ArrTime is the real Departure Time and Arrival Time

In [72]:
df1['DepTime_Formatted'] = df1['DepTime'].apply(format_hour)

In [73]:
df1['ArrTime_Formatted'] = df1['ArrTime'].apply(format_hour)

## Putting Scheduled Departure Time, Scheduled Arrival Time, Departure Time and Arrival Time togerther

In [58]:
df1.loc[:, ['CRSDepTime_Formatted', 'CRSArrTime_Formatted', 'DepTime_Formatted', 'ArrTime_Formatted']]

,CRSDepTime_Formatted,CRSArrTime_Formatted,DepTime_Formatted,ArrTime_Formatted
0,19:55:00,22:25:00,20:03:00,22:11:00
1,07:35:00,10:00:00,07:54:00,10:02:00
2,06:20:00,07:50:00,06:28:00,08:04:00
3,09:30:00,11:00:00,09:26:00,10:54:00
4,17:55:00,19:25:00,18:29:00,19:59:00
5,19:15:00,21:10:00,19:40:00,21:21:00
6,18:30:00,19:40:00,19:37:00,20:37:00
7,10:40:00,11:50:00,10:39:00,11:32:00
8,06:15:00,06:50:00,06:17:00,06:52:00
9,16:20:00,16:55:00,16:20:00,16:39:00
10,07:00:00,09:15:00,07:06:00,09:16:00
11,15:10:00,17:25:00,16:44:00,18:45:00
12,14:30:00,14:25:00,14:26:00,14:26:00
13,07:15:00,07:10:00,07:15:00,07:20:00
14,17:00:00,16:55:00,17:02:00,16:51:00
15,10:20:00,10:10:00,10:29:00,10:21:00
16,14:25:00,16:25:00,14:52:00,16:40:00
17,07:45:00,09:55:00,07:54:00,09:40:00
18,12:55:00,15:10:00,13:23:00,15:26:00
19,13:25:00,14:35:00,14:16:00,15:12:00
20,07:05:00,08:10:00,07:06:00,08:07:00
21,16:25:00,17:35:00,16:57:00,17:54:00
22,18:40:00,19:50:00,19:00:00,19:56:00
23,10:30:00,11:40:00,10:39:00,11:33:00
24,08:00:00,09:10:00,08:01:00,09:02:00
25,14:55:00,16:05:00,15:20:00,16:19:00
26,12:55:00,16:10:00,14:22:00,16:57:00
27,19:25:00,22:35:00,19:54:00,22:39:00
28,06:35:00,09:45:00,06:36:00,09:21:00
29,07:30:00,10:20:00,07:34:00,09:58:00
...,...,...,...,...
7009698,16:35:00,17:58:00,16:25:00,17:44:00
7009699,12:21:00,13:59:00,12:54:00,14:20:00
7009700,18:45:00,20:06:00,18:42:00,19:53:00
7009701,15:00:00,16:42:00,15:28:00,17:20:00
7009702,15:22:00,18:23:00,15:31:00,18:22:00
7009703,19:10:00,20:16:00,19:10:00,20:17:00
7009704,14:45:00,16:22:00,14:41:00,16:04:00
7009705,08:30:00,10:08:00,09:21:00,11:12:00
7009706,14:40:00,17:04:00,14:35:00,17:01:00
7009707,17:55:00,20:15:00,17:50:00,20:10:00
7009708,07:10:00,08:37:00,07:06:00,08:50:00
7009709,15:20:00,17:18:00,15:52:00,17:35:00
7009710,12:20:00,15:52:00,12:50:00,16:17:00
7009711,10:41:00,13:03:00,10:33:00,12:55:00
7009712,08:43:00,10:21:00,08:40:00,10:25:00
7009713,08:15:00,15:26:00,08:10:00,15:04:00
7009714,05:45:00,06:50:00,05:47:00,06:46:00
7009715,08:50:00,10:05:00,08:48:00,10:24:00
7009716,09:36:00,11:19:00,09:36:00,11:14:00
7009717,06:00:00,07:49:00,06:57:00,09:04:00
7009718,08:47:00,10:10:00,10:07:00,11:49:00
7009719,06:40:00,07:53:00,06:38:00,08:08:00
7009720,08:00:00,10:26:00,07:56:00,10:32:00
7009721,06:15:00,09:07:00,06:12:00,09:23:00
7009722,07:50:00,08:59:00,07:49:00,09:01:00
7009723,09:59:00,11:50:00,10:02:00,12:04:00
7009724,08:35:00,10:23:00,08:34:00,10:21:00
7009725,07:00:00,08:56:00,06:55:00,08:56:00
7009726,12:40:00,14:37:00,12:51:00,14:46:00
7009727,11:03:00,14:18:00,11:10:00,14:13:00

### Combine DayOfMonth, Month, Year

In [74]:
df1['Day'] = df1['DayofMonth']

In [75]:
df1['DepDate'] = pd.to_datetime(df1[['Year','Month', 'Day']])

In [76]:
def date_time_combine(r):
    if pd.isnull(r[0]) or pd.isnull(r[1]):
        return np.nan
    else:
        return datetime.datetime.combine(r[0], r[1])
def create_scheduled_dep_time(df, col):
    dt = []
    for index, cols in df1[['DepDate', col]].iterrows():
        if pd.isnull(cols[1]):
            dt.append(np.nan)
        elif float(cols[1]) == 2400:
            cols[0] += datetime.timedelta(days = 1)
            cols[1] = datetime.time(0,0)
            dt.append(date_time_combine(cols))
        else:
            cols[1] = format_hour(cols[1])
            dt.append(date_time_combine(cols))
    return pd.Series(dt)

### Combine the scheduled departure time and departure date

In [77]:
df1['CRSDep_Date_Time'] = create_scheduled_dep_time(df1, 'CRSDepTime')

In [64]:
df1['CRSDep_Date_Time']

0         2008-01-03 19:55:00
1         2008-01-03 07:35:00
2         2008-01-03 06:20:00
3         2008-01-03 09:30:00
4         2008-01-03 17:55:00
5         2008-01-03 19:15:00
6         2008-01-03 18:30:00
7         2008-01-03 10:40:00
8         2008-01-03 06:15:00
9         2008-01-03 16:20:00
10        2008-01-03 07:00:00
11        2008-01-03 15:10:00
12        2008-01-03 14:30:00
13        2008-01-03 07:15:00
14        2008-01-03 17:00:00
15        2008-01-03 10:20:00
16        2008-01-03 14:25:00
17        2008-01-03 07:45:00
18        2008-01-03 12:55:00
19        2008-01-03 13:25:00
20        2008-01-03 07:05:00
21        2008-01-03 16:25:00
22        2008-01-03 18:40:00
23        2008-01-03 10:30:00
24        2008-01-03 08:00:00
25        2008-01-03 14:55:00
26        2008-01-03 12:55:00
27        2008-01-03 19:25:00
28        2008-01-03 06:35:00
29        2008-01-03 07:30:00
                  ...
7009698   2008-12-13 16:35:00
7009699   2008-12-13 12:21:00
7009700   2008-12-13 18:45:00
7009701   2008-12-13 15:00:00
7009702   2008-12-13 15:22:00
7009703   2008-12-13 19:10:00
7009704   2008-12-13 14:45:00
7009705   2008-12-13 08:30:00
7009706   2008-12-13 14:40:00
7009707   2008-12-13 17:55:00
7009708   2008-12-13 07:10:00
7009709   2008-12-13 15:20:00
7009710   2008-12-13 12:20:00
7009711   2008-12-13 10:41:00
7009712   2008-12-13 08:43:00
7009713   2008-12-13 08:15:00
7009714   2008-12-13 05:45:00
7009715   2008-12-13 08:50:00
7009716   2008-12-13 09:36:00
7009717   2008-12-13 06:00:00
7009718   2008-12-13 08:47:00
7009719   2008-12-13 06:40:00
7009720   2008-12-13 08:00:00
7009721   2008-12-13 06:15:00
7009722   2008-12-13 07:50:00
7009723   2008-12-13 09:59:00
7009724   2008-12-13 08:35:00
7009725   2008-12-13 07:00:00
7009726   2008-12-13 12:40:00
7009727   2008-12-13 11:03:00
Name: CRSDep_Date_Time, Length: 7009728, dtype: datetime64[ns]

### Putting all the necessary features together
In this model, we will consider these following features: 
- UniqueCarrier
- Origin
- Dest
- DepTime_Formatted
- DepDelay
- CRSArrTime_Formatted
- ArrTime_Formatted
- ArrDelay
- ActualElapsedTime
- CRSElapsedTime

In [78]:
notUsedFeatures = ['TaxiIn', 'TaxiOut', 'Year', 'Month', 'DayofMonth', 'DayOfWeek', "DepDate", 'NASDelay', 'WeatherDelay', 'CarrierDelay', 'SecurityDelay', 'LateAircraftDelay', 'Cancelled', 'CancellationCode', 'Diverted', 'AirTime', 'FlightNum', 'TailNum']
df1.drop(notUsedFeatures, axis = 1, inplace=True)
df1 = df1[['UniqueCarrier', 'Origin', 'Dest', 'CRSDep_Date_Time', 'DepTime_Formatted', 'DepDelay', 'CRSArrTime_Formatted', 'ArrTime_Formatted', 'ArrDelay', 'CRSElapsedTime', 'ActualElapsedTime']]

In [67]:
df1

,UniqueCarrier,Origin,Dest,CRSDep_Date_Time,DepTime_Formatted,DepDelay,CRSArrTime_Formatted,ArrTime,ArrDelay,CRSElapsedTime,ActualElapsedTime
0,WN,IAD,TPA,2008-01-03 19:55:00,20:03:00,8.0,22:25:00,2211.0,-14.0,150.0,128.0
1,WN,IAD,TPA,2008-01-03 07:35:00,07:54:00,19.0,10:00:00,1002.0,2.0,145.0,128.0
2,WN,IND,BWI,2008-01-03 06:20:00,06:28:00,8.0,07:50:00,804.0,14.0,90.0,96.0
3,WN,IND,BWI,2008-01-03 09:30:00,09:26:00,-4.0,11:00:00,1054.0,-6.0,90.0,88.0
4,WN,IND,BWI,2008-01-03 17:55:00,18:29:00,34.0,19:25:00,1959.0,34.0,90.0,90.0
5,WN,IND,JAX,2008-01-03 19:15:00,19:40:00,25.0,21:10:00,2121.0,11.0,115.0,101.0
6,WN,IND,LAS,2008-01-03 18:30:00,19:37:00,67.0,19:40:00,2037.0,57.0,250.0,240.0
7,WN,IND,LAS,2008-01-03 10:40:00,10:39:00,-1.0,11:50:00,1132.0,-18.0,250.0,233.0
8,WN,IND,MCI,2008-01-03 06:15:00,06:17:00,2.0,06:50:00,652.0,2.0,95.0,95.0
9,WN,IND,MCI,2008-01-03 16:20:00,16:20:00,0.0,16:55:00,1639.0,-16.0,95.0,79.0
10,WN,IND,MCO,2008-01-03 07:00:00,07:06:00,6.0,09:15:00,916.0,1.0,135.0,130.0
11,WN,IND,MCO,2008-01-03 15:10:00,16:44:00,94.0,17:25:00,1845.0,80.0,135.0,121.0
12,WN,IND,MDW,2008-01-03 14:30:00,14:26:00,-4.0,14:25:00,1426.0,1.0,55.0,60.0
13,WN,IND,MDW,2008-01-03 07:15:00,07:15:00,0.0,07:10:00,720.0,10.0,55.0,65.0
14,WN,IND,MDW,2008-01-03 17:00:00,17:02:00,2.0,16:55:00,1651.0,-4.0,55.0,49.0
15,WN,IND,MDW,2008-01-03 10:20:00,10:29:00,9.0,10:10:00,1021.0,11.0,50.0,52.0
16,WN,IND,PHX,2008-01-03 14:25:00,14:52:00,27.0,16:25:00,1640.0,15.0,240.0,228.0
17,WN,IND,PHX,2008-01-03 07:45:00,07:54:00,9.0,09:55:00,940.0,-15.0,250.0,226.0
18,WN,IND,TPA,2008-01-03 12:55:00,13:23:00,28.0,15:10:00,1526.0,16.0,135.0,123.0
19,WN,ISP,BWI,2008-01-03 13:25:00,14:16:00,51.0,14:35:00,1512.0,37.0,70.0,56.0
20,WN,ISP,BWI,2008-01-03 07:05:00,07:06:00,1.0,08:10:00,807.0,-3.0,65.0,61.0
21,WN,ISP,BWI,2008-01-03 16:25:00,16:57:00,32.0,17:35:00,1754.0,19.0,70.0,57.0
22,WN,ISP,BWI,2008-01-03 18:40:00,19:00:00,20.0,19:50:00,1956.0,6.0,70.0,56.0
23,WN,ISP,BWI,2008-01-03 10:30:00,10:39:00,9.0,11:40:00,1133.0,-7.0,70.0,54.0
24,WN,ISP,BWI,2008-01-03 08:00:00,08:01:00,1.0,09:10:00,902.0,-8.0,70.0,61.0
25,WN,ISP,BWI,2008-01-03 14:55:00,15:20:00,25.0,16:05:00,1619.0,14.0,70.0,59.0
26,WN,ISP,FLL,2008-01-03 12:55:00,14:22:00,87.0,16:10:00,1657.0,47.0,195.0,155.0
27,WN,ISP,FLL,2008-01-03 19:25:00,19:54:00,29.0,22:35:00,2239.0,4.0,190.0,165.0
28,WN,ISP,FLL,2008-01-03 06:35:00,06:36:00,1.0,09:45:00,921.0,-24.0,190.0,165.0
29,WN,ISP,LAS,2008-01-03 07:30:00,07:34:00,4.0,10:20:00,958.0,-22.0,350.0,324.0
...,...,...,...,...,...,...,...,...,...,...,...
7009698,DL,CLT,ATL,2008-12-13 16:35:00,16:25:00,-10.0,17:58:00,1744.0,-14.0,83.0,79.0
7009699,DL,IND,ATL,2008-12-13 12:21:00,12:54:00,33.0,13:59:00,1420.0,21.0,98.0,86.0
7009700,DL,ATL,SDF,2008-12-13 18:45:00,18:42:00,-3.0,20:06:00,1953.0,-13.0,81.0,71.0
7009701,DL,SLC,PHX,2008-12-13 15:00:00,15:28:00,28.0,16:42:00,1720.0,38.0,102.0,112.0
7009702,DL,MCI,ATL,2008-12-13 15:22:00,15:31:00,9.0,18:23:00,1822.0,-1.0,121.0,111.0
7009703,DL,ATL,CHS,2008-12-13 19:10:00,19:10:00,0.0,20:16:00,2017.0,1.0,66.0,67.0
7009704,DL,IND,ATL,2008-12-13 14:45:00,14:41:00,-4.0,16:22:00,1604.0,-18.0,97.0,83.0
7009705,DL,ATL,PBI,2008-12-13 08:30:00,09:21:00,51.0,10:08:00,1112.0,64.0,98.0,111.0
7009706,DL,MSY,ATL,2008-12-13 14:40:00,14:35:00,-5.0,17:04:00,1701.0,-3.0,84.0,86.0
7009707,DL,ATL,BDL,2008-12-13 17:55:00,17:50:00,-5.0,20:15:00,2010.0,-5.0,140.0,140.0
7009708,DL,LEX,ATL,2008-12-13 07:10:00,07:06:00,-4.0,08:37:00,850.0,13.0,87.0,104.0
7009709,DL,HSV,ATL,2008-12-13 15:20:00,15:52:00,32.0,17:18:00,1735.0,17.0,58.0,43.0
7009710,DL,MSP,ATL,2008-12-13 12:20:00,12:50:00,30.0,15:52:00,1617.0,25.0,152.0,147.0
7009711,DL,MSY,ATL,2008-12-13 10:41:00,10:33:00,-8.0,13:03:00,1255.0,-8.0,82.0,82.0
7009712,DL,SLC,DEN,2008-12-13 08:43:00,08:40:00,-3.0,10:21:00,1025.0,4.0,98.0,105.0
7009713,DL,LAX,CVG,2008-12-13 08:15:00,08:10:00,-5.0,15:26:00,1504.0,-22.0,251.0,234.0
7009714,DL,SAV,ATL,2008-12-13 05:45:00,05:47:00,2.0,06:50:00,646.0,-4.0,65.0,59.0
7009715,DL,ATL,MCI,2008-12-13 08:50:00,08:48:00,-2.0,10:05:00,1024.0,19.0,135.0,156.0
7009716,DL,ATL,RSW,2008-12-13 09:36:00,09:36:00,0.0,11:19:00,1114.0,-5.0,103.0,98.0
7009717,DL,RIC,ATL,2008-12-13 06:00:00,06:57:00,57.0,07:49:00,904.0,75.0,109.0,127.0
7009718,DL,ATL,IAH,2008-12-13 08:47:00,10:07:00,80.0,10:10:00,1149.0,99.0,143.0,162.0
7009719,DL,JAX,ATL,2008-12-13 06:40:00,06:38:00,-2.0,07:53:00,808.0,15.0,73.0,90.0
7009720,DL,MSY,ATL,2008-12-13 08:00:00,07:56:00,-4.0,10:26:00,1032.0,6.0,86.0,96.0
7009721,DL,GEG,SLC,2008-12-13 06:15:00,06:12:00,-3.0,09:07:00,923.0,16.0,112.0,131.0
7009722,DL,SAV,ATL,2008-12-13 07:50:00,07:49:00,-1.0,08:59:00,901.0,2.0,69.0,72.0
7009723,DL,ATL,IAD,2008-12-13 09:59:00,10:02:00,3.0,11:50:00,1204.0,14.0,111.0,122.0
7009724,DL,ATL,SAT,2008-12-13 08:35:00,08:34:00,-1.0,10:23:00,1021.0,-2.0,168.0,167.0
7009725,DL,PBI,ATL,2008-12-13 07:00:00,06:55:00,-5.0,08:56:00,856.0,0.0,116.0,121.0
7009726,DL,IAD,ATL,2008-12-13 12:40:00,12:51:00,11.0,14:37:00,1446.0,9.0,117.0,115.0
7009727,DL,SAT,ATL,2008-12-13 11:03:00,11:10:00,7.0,14:18:00,1413.0,-5.0,135.0,123.0

### Examine the dataset
Drop the records with NaN values

In [80]:
df1.dropna(inplace=True)

In [81]:
df1.describe()

           DepDelay      ArrDelay  CRSElapsedTime  ActualElapsedTime
count  6.855029e+06  6.855029e+06    6.855029e+06       6.855029e+06
mean   9.923845e+00  8.168452e+00    1.290778e+02       1.273224e+02
std    3.520386e+01  3.850194e+01    6.953271e+01       7.018731e+01
min   -5.340000e+02 -5.190000e+02   -1.410000e+02       1.200000e+01
25%   -4.000000e+00 -1.000000e+01    8.000000e+01       7.700000e+01
50%   -1.000000e+00 -2.000000e+00    1.110000e+02       1.100000e+02
75%    8.000000e+00  1.200000e+01    1.590000e+02       1.570000e+02
max    2.467000e+03  2.461000e+03    6.600000e+02       1.379000e+03

In [86]:
carriers = pd.read_csv('../data/carriers.csv')

In [87]:
carriers

        Code                                   Description
0        02Q                                 Titan Airways
1        04Q                            Tradewind Aviation
2        05Q                           Comlux Aviation, AG
3        06Q                 Master Top Linhas Aereas Ltd.
4        07Q                           Flair Airlines Ltd.
5        09Q                                Swift Air, LLC
6        0BQ                                           DCA
7        0CQ                          ACM AIR CHARTER GmbH
8        0FQ          Maine Aviation Aircraft Charter, LLC
9        0GQ  Inter Island Airways, d/b/a Inter Island Air
10       0HQ       Polar Airlines de Mexico d/b/a Nova Air
11        0J                                    JetClub AG
12       0JQ                               Vision Airlines
13       0KQ                Mokulele Flight Services, Inc.
14       0LQ                             Metropix UK, LLP.
15       0MQ         Multi-Aero, Inc. d/b/a Air Choice One
16        0Q                           Flying Service N.V.
17        16                             PSA Airlines Inc.
18        17                             Piedmont Airlines
19        1I                       Sky Trek Int'l Airlines
20        2E                           Smokey Bay Air Inc.
21        2F                       Frontier Flying Service
22        2M                       Midway Express Airlines
23        2O                            Island Air Service
24        2R                                     Regal Air
25        2T                     Canada 3000 Airlines Ltd.
26        2U                       Valley Air Express Inc.
27        37                                      Zeal 320
28        3C                             Regions Air, Inc.
29        3F                         Pacific Airways, Inc.
...      ...                                           ...
1461      YB                    Trans Continental Airlines
1462     YBQ                               Yellow Bird Air
1463      YM                           Royal West Airlines
1464      YR    Scenic Airlines Inc. d/b/a Scenic Airlines
1465      YV                            Mesa Airlines Inc.
1466      YX                         Midwest Airline, Inc.
1467      Z3                                   PM Air, LLC
1468  Z3 (1)                                       Promech
1469      ZA                            Accessair Holdings
1470     ZAQ                          Zas Airline Of Egypt
1471      ZB                              Monarch Airlines
1472      ZE                          Lineas Aereas Azteca
1473     ZFZ                     Mcphillips Flying Service
1474     ZIA                                Air New Mexico
1475      ZK                          Great Lakes Airlines
1476     ZKQ                          Zantop International
1477      ZL                                     Affretair
1478     ZMZ                   Winnipesaukee Aviation Inc.
1479      ZN                             Key Airlines Inc.
1480      ZO                          Florida Express Inc.
1481      ZP                                Air St. Thomas
1482      ZQ                        Caribbean Sun Airlines
1483      ZS                            Hispaniola Airways
1484     ZUQ                           Zuliana De Aviacion
1485      ZV                              Air Midwest Inc.
1486      ZW                   Air Wisconsin Airlines Corp
1487      ZX                                  Air Georgian
1488  ZX (1)                                    Airbc Ltd.
1489      ZY                        Atlantic Gulf Airlines
1490     ZYZ                          Skyway Aviation Inc.

[1491 rows x 2 columns]

In [88]:
carriers_abbr = carriers.set_index('Code')['Description'].to_dict()

In [91]:
def get_stats(group):
    return {'min': group.min(), 'max': group.max(),
            'count': group.count(), 'mean': group.mean()}
#_______________________________________________________________
# Creation of a dataframe with statitical infos on each airline:
global_stats = df1['DepDelay'].groupby(df1['UniqueCarrier']).apply(get_stats).unstack()
global_stats = global_stats.sort_values('count')
global_stats

                   count     max       mean    min
UniqueCarrier
AQ                7752.0   336.0  -1.482456  -61.0
HA               61212.0   963.0   0.439211 -534.0
F9               95384.0   817.0   5.903107  -25.0
AS              148492.0   947.0   6.717439  -79.0
OH              190695.0   960.0  11.510150  -70.0
B6              192114.0   846.0  12.572827  -70.0
YV              245131.0   607.0  11.952744  -92.0
9E              254322.0  1127.0   6.733861  -42.0
FL              258713.0  1206.0   9.229818  -62.0
EV              274867.0   965.0  11.922875  -61.0
CO              293855.0  1011.0  13.135781  -28.0
NW              344110.0  2467.0   6.438267  -35.0
XE              363414.0   859.0  11.328870  -71.0
UA              437979.0  1303.0  14.064279  -34.0
DL              443934.0  1003.0   7.975474  -38.0
US              446086.0   886.0   5.687228  -40.0
MQ              471161.0  1710.0  10.628900  -40.0
OO              553412.0   996.0   7.406290  -67.0
AA              585485.0  1521.0  13.228520  -64.0
WN             1186911.0   668.0  10.323081  -38.0

### Model 1: One Airline, One Airport

In [99]:
train = df1[df1['CRSDep_Date_Time'].apply(lambda x:x.date()) < datetime.date(2008, 5, 23)]
test = df1[df1['CRSDep_Date_Time'].apply(lambda x:x.date()) > datetime.date(2008, 5, 23)]
df2 = train

In [100]:
df2

,UniqueCarrier,Origin,Dest,CRSDep_Date_Time,DepTime_Formatted,DepDelay,CRSArrTime_Formatted,ArrTime_Formatted,ArrDelay,CRSElapsedTime,ActualElapsedTime
0,WN,IAD,TPA,2008-01-03 19:55:00,20:03:00,8.0,22:25:00,22:11:00,-14.0,150.0,128.0
1,WN,IAD,TPA,2008-01-03 07:35:00,07:54:00,19.0,10:00:00,10:02:00,2.0,145.0,128.0
2,WN,IND,BWI,2008-01-03 06:20:00,06:28:00,8.0,07:50:00,08:04:00,14.0,90.0,96.0
3,WN,IND,BWI,2008-01-03 09:30:00,09:26:00,-4.0,11:00:00,10:54:00,-6.0,90.0,88.0
4,WN,IND,BWI,2008-01-03 17:55:00,18:29:00,34.0,19:25:00,19:59:00,34.0,90.0,90.0
5,WN,IND,JAX,2008-01-03 19:15:00,19:40:00,25.0,21:10:00,21:21:00,11.0,115.0,101.0
6,WN,IND,LAS,2008-01-03 18:30:00,19:37:00,67.0,19:40:00,20:37:00,57.0,250.0,240.0
7,WN,IND,LAS,2008-01-03 10:40:00,10:39:00,-1.0,11:50:00,11:32:00,-18.0,250.0,233.0
8,WN,IND,MCI,2008-01-03 06:15:00,06:17:00,2.0,06:50:00,06:52:00,2.0,95.0,95.0
9,WN,IND,MCI,2008-01-03 16:20:00,16:20:00,0.0,16:55:00,16:39:00,-16.0,95.0,79.0
10,WN,IND,MCO,2008-01-03 07:00:00,07:06:00,6.0,09:15:00,09:16:00,1.0,135.0,130.0
11,WN,IND,MCO,2008-01-03 15:10:00,16:44:00,94.0,17:25:00,18:45:00,80.0,135.0,121.0
12,WN,IND,MDW,2008-01-03 14:30:00,14:26:00,-4.0,14:25:00,14:26:00,1.0,55.0,60.0
13,WN,IND,MDW,2008-01-03 07:15:00,07:15:00,0.0,07:10:00,07:20:00,10.0,55.0,65.0
14,WN,IND,MDW,2008-01-03 17:00:00,17:02:00,2.0,16:55:00,16:51:00,-4.0,55.0,49.0
15,WN,IND,MDW,2008-01-03 10:20:00,10:29:00,9.0,10:10:00,10:21:00,11.0,50.0,52.0
16,WN,IND,PHX,2008-01-03 14:25:00,14:52:00,27.0,16:25:00,16:40:00,15.0,240.0,228.0
17,WN,IND,PHX,2008-01-03 07:45:00,07:54:00,9.0,09:55:00,09:40:00,-15.0,250.0,226.0
18,WN,IND,TPA,2008-01-03 12:55:00,13:23:00,28.0,15:10:00,15:26:00,16.0,135.0,123.0
19,WN,ISP,BWI,2008-01-03 13:25:00,14:16:00,51.0,14:35:00,15:12:00,37.0,70.0,56.0
20,WN,ISP,BWI,2008-01-03 07:05:00,07:06:00,1.0,08:10:00,08:07:00,-3.0,65.0,61.0
21,WN,ISP,BWI,2008-01-03 16:25:00,16:57:00,32.0,17:35:00,17:54:00,19.0,70.0,57.0
22,WN,ISP,BWI,2008-01-03 18:40:00,19:00:00,20.0,19:50:00,19:56:00,6.0,70.0,56.0
23,WN,ISP,BWI,2008-01-03 10:30:00,10:39:00,9.0,11:40:00,11:33:00,-7.0,70.0,54.0
24,WN,ISP,BWI,2008-01-03 08:00:00,08:01:00,1.0,09:10:00,09:02:00,-8.0,70.0,61.0
25,WN,ISP,BWI,2008-01-03 14:55:00,15:20:00,25.0,16:05:00,16:19:00,14.0,70.0,59.0
26,WN,ISP,FLL,2008-01-03 12:55:00,14:22:00,87.0,16:10:00,16:57:00,47.0,195.0,155.0
27,WN,ISP,FLL,2008-01-03 19:25:00,19:54:00,29.0,22:35:00,22:39:00,4.0,190.0,165.0
28,WN,ISP,FLL,2008-01-03 06:35:00,06:36:00,1.0,09:45:00,09:21:00,-24.0,190.0,165.0
29,WN,ISP,LAS,2008-01-03 07:30:00,07:34:00,4.0,10:20:00,09:58:00,-22.0,350.0,324.0
...,...,...,...,...,...,...,...,...,...,...,...
2995480,DL,SAN,CVG,2008-05-18 07:20:00,07:17:00,-3.0,14:27:00,14:27:00,0.0,247.0,250.0
2995481,DL,ATL,EWR,2008-05-18 09:55:00,09:52:00,-3.0,12:17:00,12:01:00,-16.0,142.0,129.0
2995482,DL,FLL,ATL,2008-05-18 17:12:00,17:10:00,-2.0,19:09:00,19:12:00,3.0,117.0,122.0
2995483,DL,ATL,LAS,2008-05-18 20:00:00,20:10:00,10.0,21:25:00,21:21:00,-4.0,265.0,251.0
2995484,DL,ORD,ATL,2008-05-18 13:40:00,13:35:00,-5.0,16:40:00,16:38:00,-2.0,120.0,123.0
2995485,DL,ATL,JAX,2008-05-18 17:30:00,17:27:00,-3.0,18:39:00,18:49:00,10.0,69.0,82.0
2995486,DL,BWI,ATL,2008-05-18 15:25:00,15:20:00,-5.0,17:18:00,17:14:00,-4.0,113.0,114.0
2995487,DL,RDU,ATL,2008-05-18 18:20:00,18:48:00,28.0,19:49:00,20:07:00,18.0,89.0,79.0
2995488,DL,LAX,CVG,2008-05-18 23:25:00,23:24:00,-1.0,06:38:00,06:36:00,-2.0,253.0,252.0
2995489,DL,ATL,SLC,2008-05-18 12:20:00,12:24:00,4.0,14:15:00,14:25:00,10.0,235.0,241.0
2995490,DL,RDU,ATL,2008-05-18 14:38:00,14:36:00,-2.0,16:05:00,15:59:00,-6.0,87.0,83.0
2995491,DL,ATL,PDX,2008-05-18 16:55:00,16:57:00,2.0,19:21:00,19:18:00,-3.0,326.0,321.0
2995492,DL,PDX,ATL,2008-05-18 11:45:00,11:45:00,0.0,19:22:00,19:20:00,-2.0,277.0,275.0
2995493,DL,PHF,ATL,2008-05-18 14:35:00,14:28:00,-7.0,16:35:00,16:36:00,1.0,120.0,128.0
2995494,DL,ATL,RDU,2008-05-18 21:20:00,21:19:00,-1.0,22:43:00,22:45:00,2.0,83.0,86.0
2995495,DL,IAD,SLC,2008-05-18 06:15:00,06:12:00,-3.0,08:53:00,08:49:00,-4.0,278.0,277.0
2995496,DL,RSW,ATL,2008-05-18 06:00:00,05:59:00,-1.0,07:42:00,07:43:00,1.0,102.0,104.0
2995497,DL,ATL,BWI,2008-05-18 08:36:00,08:36:00,0.0,10:25:00,10:13:00,-12.0,109.0,97.0
2995498,DL,ATL,SAT,2008-05-18 11:05:00,11:03:00,-2.0,12:35:00,12:38:00,3.0,150.0,155.0
2995499,DL,JAX,ATL,2008-05-18 09:55:00,09:53:00,-2.0,11:07:00,10:59:00,-8.0,72.0,66.0
2995500,DL,RSW,ATL,2008-05-18 13:50:00,13:46:00,-4.0,15:36:00,15:44:00,8.0,106.0,118.0
2995501,DL,ORD,ATL,2008-05-18 08:45:00,08:44:00,-1.0,11:40:00,11:45:00,5.0,115.0,121.0
2995502,DL,ATL,CHS,2008-05-18 12:25:00,12:25:00,0.0,13:32:00,13:27:00,-5.0,67.0,62.0
2995503,DL,EWR,ATL,2008-05-18 11:30:00,11:24:00,-6.0,13:42:00,13:42:00,0.0,132.0,138.0
2995504,DL,MIA,ATL,2008-05-18 18:50:00,18:55:00,5.0,20:44:00,20:50:00,6.0,114.0,115.0
2995505,DL,TPA,ATL,2008-05-18 16:20:00,16:21:00,1.0,17:54:00,17:50:00,-4.0,94.0,89.0
2995506,DL,ATL,SAN,2008-05-18 18:55:00,18:52:00,-3.0,20:45:00,20:08:00,-37.0,290.0,256.0
2995507,DL,MSY,ATL,2008-05-18 17:30:00,17:34:00,4.0,20:02:00,20:00:00,-2.0,92.0,86.0
2995508,DL,ATL,AUS,2008-05-18 11:15:00,11:12:00,-3.0,12:37:00,12:38:00,1.0,142.0,146.0
2995509,DL,JAX,ATL,2008-05-18 18:10:00,18:41:00,31.0,19:31:00,20:04:00,33.0,81.0,83.0